--
-- PostgreSQL database dump
--

\restrict 3c5Q9igtj6Go3ZRGFc718pcRIrh9RICO5fkIbexnbcTtvk3f140kmfFBv0NO432

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.cart (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    user_id bigint NOT NULL,
    event_session_id bigint NOT NULL
);


ALTER TABLE public.cart OWNER TO venueon;

--
-- Name: cart_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    sort_order integer
);


ALTER TABLE public.categories OWNER TO venueon;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment_likes; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.comment_likes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    comment_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.comment_likes OWNER TO venueon;

--
-- Name: comment_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.comment_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_hidden boolean NOT NULL,
    like_count integer,
    author_id bigint NOT NULL,
    parent_id bigint,
    post_id bigint NOT NULL
);


ALTER TABLE public.comments OWNER TO venueon;

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communities; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.communities (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    is_public boolean,
    member_count integer,
    name character varying(255) NOT NULL,
    thumbnail_url character varying(255),
    creator_id bigint NOT NULL,
    event_id bigint
);


ALTER TABLE public.communities OWNER TO venueon;

--
-- Name: communities_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.communities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: community_members; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.community_members (
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    role character varying(255) NOT NULL,
    community_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT community_members_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MEMBER'::character varying])::text[])))
);


ALTER TABLE public.community_members OWNER TO venueon;

--
-- Name: community_members_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.community_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.community_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_sessions; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.event_sessions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_attendees integer,
    description text,
    end_time timestamp(6) without time zone,
    is_default boolean,
    is_online boolean,
    location character varying(255),
    max_attendees integer,
    online_link character varying(255),
    price integer NOT NULL,
    region_sido character varying(255),
    region_sigungu character varying(255),
    sort_order integer,
    start_time timestamp(6) without time zone,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    event_id bigint NOT NULL
);


ALTER TABLE public.event_sessions OWNER TO venueon;

--
-- Name: event_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.event_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    end_date timestamp(6) without time zone,
    has_session boolean,
    is_hidden boolean NOT NULL,
    is_online boolean,
    location character varying(255),
    max_attendees integer,
    price integer NOT NULL,
    purchase_type character varying(255),
    start_date timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    thumbnail_url character varying(255),
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    category_id bigint,
    creator_id bigint NOT NULL,
    CONSTRAINT events_purchase_type_check CHECK (((purchase_type)::text = ANY ((ARRAY['SINGLE'::character varying, 'MULTI'::character varying])::text[]))),
    CONSTRAINT events_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'PREPARING'::character varying, 'ONGOING'::character varying, 'ENDED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT events_type_check CHECK (((type)::text = ANY ((ARRAY['SEMINAR'::character varying, 'CLASS'::character varying, 'MEETUP'::character varying, 'CONFERENCE'::character varying])::text[])))
);


ALTER TABLE public.events OWNER TO venueon;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO venueon;

--
-- Name: host_profiles; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.host_profiles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    manager_name character varying(255),
    org_description character varying(1000),
    org_name character varying(255) NOT NULL,
    org_number character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.host_profiles OWNER TO venueon;

--
-- Name: host_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.host_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.host_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    amount integer NOT NULL,
    display_ordered_at timestamp(6) without time zone,
    ordered_at timestamp(6) without time zone NOT NULL,
    paid_at timestamp(6) without time zone,
    payment_method character varying(255),
    quantity integer NOT NULL,
    status character varying(255) NOT NULL,
    toss_order_id character varying(255),
    toss_payment_key character varying(255),
    event_id bigint NOT NULL,
    session_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying, 'REGISTERED'::character varying, 'REFUND_REQUESTED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO venueon;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_bookmarks; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.post_bookmarks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.post_bookmarks OWNER TO venueon;

--
-- Name: post_bookmarks_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.post_bookmarks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_bookmarks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_likes; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.post_likes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.post_likes OWNER TO venueon;

--
-- Name: post_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.post_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: posts; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.posts (
    id bigint NOT NULL,
    comment_count integer,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_hidden boolean NOT NULL,
    is_notice boolean NOT NULL,
    is_pinned boolean NOT NULL,
    like_count integer,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    view_count integer,
    author_id bigint NOT NULL,
    community_id bigint NOT NULL,
    CONSTRAINT posts_type_check CHECK (((type)::text = ANY ((ARRAY['GENERAL'::character varying, 'REVIEW'::character varying, 'QUESTION'::character varying, 'NOTICE'::character varying])::text[])))
);


ALTER TABLE public.posts OWNER TO venueon;

--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refunds; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.refunds (
    id bigint NOT NULL,
    amount integer NOT NULL,
    processed_at timestamp(6) without time zone,
    reason character varying(255),
    requested_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    order_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT refunds_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.refunds OWNER TO venueon;

--
-- Name: refunds_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.refunds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refunds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reports; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.reports (
    id bigint NOT NULL,
    admin_action character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    detail text,
    reason character varying(255) NOT NULL,
    resolved_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    target_id bigint NOT NULL,
    target_type character varying(255) NOT NULL,
    reporter_id bigint NOT NULL,
    CONSTRAINT reports_admin_action_check CHECK (((admin_action)::text = ANY ((ARRAY['DELETE'::character varying, 'HIDE'::character varying, 'WARN'::character varying, 'DISMISS'::character varying])::text[]))),
    CONSTRAINT reports_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RESOLVED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT reports_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['EVENT'::character varying, 'POST'::character varying, 'COMMENT'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.reports OWNER TO venueon;

--
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_categories; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.user_categories (
    user_id bigint NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.user_categories OWNER TO venueon;

--
-- Name: users; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    is_badge_visible boolean NOT NULL,
    nickname character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255),
    profile_img character varying(255),
    provider character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'HOST'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO venueon;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist; Type: TABLE; Schema: public; Owner: venueon
--

CREATE TABLE public.wishlist (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    event_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.wishlist OWNER TO venueon;

--
-- Name: wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: venueon
--

ALTER TABLE public.wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: comment_likes comment_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT comment_likes_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: communities communities_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.communities
    ADD CONSTRAINT communities_pkey PRIMARY KEY (id);


--
-- Name: community_members community_members_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.community_members
    ADD CONSTRAINT community_members_pkey PRIMARY KEY (id);


--
-- Name: event_sessions event_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.event_sessions
    ADD CONSTRAINT event_sessions_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: host_profiles host_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.host_profiles
    ADD CONSTRAINT host_profiles_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: post_bookmarks post_bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT post_bookmarks_pkey PRIMARY KEY (id);


--
-- Name: post_likes post_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: refunds refunds_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT refunds_pkey PRIMARY KEY (id);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);


--
-- Name: post_bookmarks uk3hralg8r0y2lc96pbp3km8mrj; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT uk3hralg8r0y2lc96pbp3km8mrj UNIQUE (post_id, user_id);


--
-- Name: host_profiles uk3r0wuhflvro1bablqccnr8hhk; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.host_profiles
    ADD CONSTRAINT uk3r0wuhflvro1bablqccnr8hhk UNIQUE (user_id);


--
-- Name: post_likes uk5l2rj28vw5oj6f7ox746grokg; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT uk5l2rj28vw5oj6f7ox746grokg UNIQUE (post_id, user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: community_members ukfr78n3lo0omh8or6dipyem6ii; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.community_members
    ADD CONSTRAINT ukfr78n3lo0omh8or6dipyem6ii UNIQUE (community_id, user_id);


--
-- Name: comment_likes ukgu1pee3567af29uutdfy0fcjd; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT ukgu1pee3567af29uutdfy0fcjd UNIQUE (comment_id, user_id);


--
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wishlist wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: venueon
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: comment_likes fk3wa5u7bs1p1o9hmavtgdgk1go; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT fk3wa5u7bs1p1o9hmavtgdgk1go FOREIGN KEY (comment_id) REFERENCES public.comments(id);


--
-- Name: orders fk43g2yroy6l7lfomw37wajkqrn; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk43g2yroy6l7lfomw37wajkqrn FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: event_sessions fk4j89lx7pd3n6ugkg9bcmgpu5j; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.event_sessions
    ADD CONSTRAINT fk4j89lx7pd3n6ugkg9bcmgpu5j FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: comment_likes fk6h3lbneryl5pyb9ykaju7werx; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT fk6h3lbneryl5pyb9ykaju7werx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_categories fk6r91537otve5embvcuv40is3j; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.user_categories
    ADD CONSTRAINT fk6r91537otve5embvcuv40is3j FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: posts fk6xvn0811tkyo3nfjk2xvqx6ns; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk6xvn0811tkyo3nfjk2xvqx6ns FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: events fk7ljm71n1057envlomdxcni5hs; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk7ljm71n1057envlomdxcni5hs FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: posts fk7rk45ficmsfhe8n1dojvqt6ui; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk7rk45ficmsfhe8n1dojvqt6ui FOREIGN KEY (community_id) REFERENCES public.communities(id);


--
-- Name: post_bookmarks fk9b5c09u5arho7ei76d78bn7ww; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT fk9b5c09u5arho7ei76d78bn7ww FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: post_likes fka5wxsgl4doibhbed9gm7ikie2; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT fka5wxsgl4doibhbed9gm7ikie2 FOREIGN KEY (post_id) REFERENCES public.posts(id);


--
-- Name: post_bookmarks fkclpw1l6wrci96rfj0dtt3bfah; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT fkclpw1l6wrci96rfj0dtt3bfah FOREIGN KEY (post_id) REFERENCES public.posts(id);


--
-- Name: reports fkd3qiw2om5d2oh5xb7fbdcq225; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fkd3qiw2om5d2oh5xb7fbdcq225 FOREIGN KEY (reporter_id) REFERENCES public.users(id);


--
-- Name: user_categories fkdqpxght56isds8smi1frxg0xo; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.user_categories
    ADD CONSTRAINT fkdqpxght56isds8smi1frxg0xo FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: communities fkehds1lhi1y9a8rweslp1esncn; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.communities
    ADD CONSTRAINT fkehds1lhi1y9a8rweslp1esncn FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: cart fkg5uhi8vpsuy0lgloxk2h4w5o6; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT fkg5uhi8vpsuy0lgloxk2h4w5o6 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: orders fkgd5ammciw5sgjqy5hafdtjipc; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkgd5ammciw5sgjqy5hafdtjipc FOREIGN KEY (session_id) REFERENCES public.event_sessions(id);


--
-- Name: comments fkh4c7lvsc298whoyd4w9ta25cr; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id) REFERENCES public.posts(id);


--
-- Name: communities fkhi7jr3il90nrhisu3htfl4ks; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.communities
    ADD CONSTRAINT fkhi7jr3il90nrhisu3htfl4ks FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: post_likes fkkgau5n0nlewg6o9lr4yibqgxj; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT fkkgau5n0nlewg6o9lr4yibqgxj FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: comments fklri30okf66phtcgbe5pok7cc0; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fklri30okf66phtcgbe5pok7cc0 FOREIGN KEY (parent_id) REFERENCES public.comments(id);


--
-- Name: community_members fkme7k1stbnwi6cpmm8a6sgcikn; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.community_members
    ADD CONSTRAINT fkme7k1stbnwi6cpmm8a6sgcikn FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: host_profiles fkmoas5i4ry1m9mwgbgb1jdrhli; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.host_profiles
    ADD CONSTRAINT fkmoas5i4ry1m9mwgbgb1jdrhli FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: comments fkn2na60ukhs76ibtpt9burkm27; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkn2na60ukhs76ibtpt9burkm27 FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: events fko6mla8j1p5bokt4dxrlmgwc28; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fko6mla8j1p5bokt4dxrlmgwc28 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: cart fkoqqsgaf5yiv0d60mxoyytgtfa; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT fkoqqsgaf5yiv0d60mxoyytgtfa FOREIGN KEY (event_session_id) REFERENCES public.event_sessions(id);


--
-- Name: community_members fkqn9g17tqcwnoy41o2am9fnlep; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.community_members
    ADD CONSTRAINT fkqn9g17tqcwnoy41o2am9fnlep FOREIGN KEY (community_id) REFERENCES public.communities(id);


--
-- Name: refunds fkrtxief4co3k1lfklj7n05m8mo; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT fkrtxief4co3k1lfklj7n05m8mo FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: refunds fksk9rqm7f6y8b1g0qob018hdm7; Type: FK CONSTRAINT; Schema: public; Owner: venueon
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT fksk9rqm7f6y8b1g0qob018hdm7 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 3c5Q9igtj6Go3ZRGFc718pcRIrh9RICO5fkIbexnbcTtvk3f140kmfFBv0NO432

