# ===== Common Settings =====
spring.application.name=venueon-backend
spring.profiles.active=dev

server.port=8080

# JPA Common
spring.jpa.open-in-view=false

# Multipart File Upload (기본 1MB → 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Common
jwt.expiration=3600000

# Static Resources
spring.mvc.static-path-pattern=/**

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
