# ===== Common Settings =====
spring.application.name=venueon-backend
spring.profiles.active=dev

server.port=8080

# JPA Common
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT Common
jwt.expiration=3600000

# Static Resources
spring.mvc.static-path-pattern=/**

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
